services:
  mcp-server:
    image: mcp-server-final  # <-- USE A IMAGEM CONSTRUÃDA
    # build:
    #   context: .
    #   dockerfile: docker/Dockerfile
    container_name: mcp-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3333:3333"
    dns:
      - 8.8.8.8
      - 1.1.1.1