services:
  mcp-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # image: mcp-server-final  # <-- REMOVA OU COMENTE ESTA LINHA TEMPORÁRIA
    container_name: mcp-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3333:3333"
    dns:
      - 8.8.8.8 # DNS primário (Google)
      - 1.1.1.1 # DNS secundário (Cloudflare)